# Application Name
spring.application.name=request-to-pay-service

# Observability - Tracing Configuration
management.tracing.enabled=true
management.tracing.sampling.probability=1.0 # Sample all requests for tracing. In production, you might lower this to 0.1 (10%).

# Observability - Endpoint Exposure
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
